services:
  db:
    container_name: 'project-db'
    image: postgres
    volumes:
      - storage_db:/var/lib/postgres/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - project-net
  app:
    build: .
    container_name: 'project-api'
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./entrypoint.sh:/app/entrypoint.sh
    depends_on:
      - db
      - redis
    networks:
      - project-net

  redis:
    container_name: 'project-redis'
    image: redis:8.2
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - project-net


volumes:
  storage_db:
  
networks:
  project-net:
    driver: bridge